version: "3.8"
services:
  frontend:
    command: npm run dev
    build:
      context: ./web
      dockerfile: ../web.Dockerfile
    networks: 
      - webnet
    develop:  
      watch:
        - path: ./web
          target: /var/web # WORKDIR in Dockerfile
          action: sync
          ignore:
            - node_modules/
        - path: ./web/package.json
          target: /var/web/package.json
          action: rebuild
    depends_on:
      - postgres
      - express
    ports:
      - '3000:3000'

  express:
    command: node server.js
    build:
      context: ./express
      dockerfile: ../express.Dockerfile
    networks: 
      - webnet
    develop:
      watch:
        - path: ./express/
          target: /var/express # WORKDIR in Dockerfile
          action: sync
          ignore:
            - node_modules/
        - path: ./express/package.json
          target: /var/express/package.json
          action: rebuild
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3001:3001'

  postgres:
    image: postgres:latest
    networks: 
      - webnet
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - ./backup_database.sql:/docker-entrypoint-initdb.d/backup_database.sql
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d test_swe -U db_user"]
        interval: 10s
        timeout: 5s
        retries: 5

networks:
  webnet:
    driver: bridge