name: Deploy to Azure VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sanitize docker-compose.yml
      run: |
        sed -i '/develop:/,/action: rebuild/d' docker-compose.yml
        cat docker-compose.yml

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: copia dei file sulla VM
      run: |  
        scp -o StrictHostKeyChecking=no -r * ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/${{ github.event.repository.name }}/

    - name: run docker compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "cd /home/${{ secrets.USER }}/${{ github.event.repository.name }} && ls && docker-compose up --build -d"