name: Deploy to Azure VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: look files
      run: ls -la

    - name: folder name
      run: |
        cd ..
        ls -la

    - name: Create SSH key file
      run: |
        echo "${{ secrets.KEY }}" > id_rsa
        chmod 600 id_rsa

    - name: copia dei file sulla VM
      run: |
        scp -i ./id_rsa -r ./${{ github.event.repository.name }}/ ${{ secrets.USER }}@${{ secrets.HOST }}:~